print('猫の名前を入力してください。')
cat_name1 = input()
print('猫の名前を入力してください。')
cat_name2 = input()
print('猫の名前を入力してください。')
cat_name3 = input()
print('猫の名前を入力してください。')
cat_name4 = input()
print('猫の名前を入力してください。')
cat_name5 = input()
print('猫の名前を入力してください。')
cat_name6 = input()
print('猫の名前を入力してください。')
cat_name7 = input()
print('猫の名前を入力してください。')
cat_name8 = input()
print('猫の名前を入力してください。')
cat_name9 = input()
print('猫の名前を入力してください。')
cat_name10 = input()
print('猫の名前は次の通り：')
print(cat_name1 + ' ' + cat_name2 + ' ' + cat_name3 + ' ' + cat_name4 + ' ' + cat_name5 + ' ' + cat_name6 + ' ' + cat_name7 + ' ' + cat_name8 + ' ' + cat_name9 + ' ' + cat_name10)
